<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15794" started-at="2020-10-17T12:28:59 IST" finished-at="2020-10-17T12:29:15 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15794" started-at="2020-10-17T12:28:59 IST" finished-at="2020-10-17T12:29:15 IST">
      <class name="automation.covid.tests.TestPositivityRatioTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:automation.covid.tests.TestPositivityRatioTest@bccb269]" name="setup" is-config="true" duration-ms="7149" started-at="2020-10-17T12:28:59 IST" finished-at="2020-10-17T12:29:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyTestPositivity()[pri:1, instance:automation.covid.tests.TestPositivityRatioTest@bccb269]" name="verifyTestPositivity" duration-ms="8426" started-at="2020-10-17T12:29:06 IST" finished-at="2020-10-17T12:29:15 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at automation.covid.pages.HomePage.getTestedPositiveRatio(HomePage.java:27)
at automation.covid.tests.TestPositivityRatioTest.verifyTestPositivity(TestPositivityRatioTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1255)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestPositivity -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:automation.covid.tests.TestPositivityRatioTest@bccb269]" name="tearDownTest" is-config="true" duration-ms="153" started-at="2020-10-17T12:29:15 IST" finished-at="2020-10-17T12:29:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
      </class> <!-- automation.covid.tests.TestPositivityRatioTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
